# Generated by Django 3.2.21 on 2023-09-16 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=100)),
                ('vacancies', models.IntegerField(blank=True, default=0, null=True)),
                ('employee_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_range', models.CharField(blank=True, default=0, max_length=40, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('job_title', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=20)),
                ('expiry_date', models.DateField(blank=True, default=None, null=True)),
                ('experience', models.CharField(choices=[('0-1 years', 'One'), ('1-2 years', 'One Two'), ('2-3 years', 'Two Three'), ('2-5 years', 'Two Five'), ('5-10 years', 'Five Ten'), ('10+ years', 'Ten Above')], default='0-1 years', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Job',
            },
        ),
        migrations.CreateModel(
            name='JobApplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('hiring_text', models.CharField(default='No Reason', max_length=400)),
                ('application_status', models.CharField(choices=[('rejected', 'Rejected'), ('shortlisted', 'Shortlisted'), ('new', 'New')], default='new', max_length=50)),
                ('jobid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
