# Generated by Django 4.2.5 on 2023-09-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplymodel',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplymodel',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
