# Generated by Django 3.2.21 on 2023-09-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Blidness', 'Blindness'), ('Partial blindness', 'Partial'), ('Hearing', 'Hearing'), ('Impairement', 'Impairement'), ('Handicap', 'Handicap'), ('Person_with_Disability', 'Person With Disability')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobapplymodel',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplymodel',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
