# Generated by Django 3.2.21 on 2023-09-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20230916_1712'),
        ('jobs', '0002_jobapplymodel_is_applied_jobapplymodel_is_saved'),
    ]

    operations = [
    ]
